version: '3.8'

services:
  web:
    build: .
    image: trading_system_image
    working_dir: /trading_system/trading_system
    command: >
      sh -c "
      python manage.py runserver 0.0.0.0:8000 & 
      celery -A trading_system worker --loglevel=info & 
      celery -A trading_system beat --loglevel=info & 
      celery -A trading_system flower --port=5555 --broker=redis://redis:6379/0
      "
    volumes:
      - .:/trading_system
    ports:
      - "8000:8000"
      - "5555:5555"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
