version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: trading_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A trading_system worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A trading_system beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  flower:
    build: .
    command: celery -A trading_system flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
