version: '3'

services:
  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '128M'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    environment:
      - TZ=Asia/Taipei
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  app:
    build: .
    image: trading_system_image:prod
    platform: linux/amd64
    working_dir: /trading_system/trading_system
    volumes:
      - ./supervisord_prod.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    # ports:
      # - "8000:8000"
      # - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2G'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - app-network
    environment:
      - TZ=Asia/Taipei
      - REDIS_HOST=redis
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '128M'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - app-network
    environment:
      - TZ=Asia/Taipei
    restart: always

networks:
  app-network:

volumes:
  redis-data: