version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '256M'
    restart: always

  app:
    build: .
    image: trading_system_image
    working_dir: /trading_system/trading_system
    command: /bin/bash -c "python manage.py runserver 0.0.0.0:8000 & celery -A trading_system worker --loglevel=info & celery -A trading_system beat --loglevel=info & celery -A trading_system flower --port=5555"
    volumes:
      - .:/trading_system
    ports:
      - "8000:8000"
      - "5555:5555"
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '1.5G'
    restart: always
