# docker-compose.override
version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  app:
    deploy:
      resources:
        limits:
          cpus: '5.0'
          memory: '4G'
        reservations:
          cpus: '4.0'
          memory: '2G'
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached

    environment:
      - PYTHONUNBUFFERED=1  # let python output display directly in the console for easier debugging

    # Permanently pause it
    # Note: Dockerfile uses supervisord to start the server by default.
    # In development, use this start it manually.
    command: sleep infinity

  redis:
    ports:
      - "6379:6379"

  nginx:
