# Generated by Django 5.0.6 on 2024-05-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="day",
        ),
        migrations.RemoveField(
            model_name="order",
            name="month",
        ),
        migrations.RemoveField(
            model_name="order",
            name="year",
        ),
    ]
