# Generated by Django 5.0.6 on 2024-05-31 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="revenue",
            old_name="diff_price",
            new_name="gain_price",
        ),
    ]
