# Generated by Django 5.0.6 on 2024-05-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceData",
            fields=[
                ("day_price_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("date", models.CharField(max_length=10)),
                ("day", models.CharField(max_length=10)),
                ("open", models.IntegerField()),
                ("high", models.IntegerField()),
                ("low", models.IntegerField()),
                ("close", models.IntegerField()),
                ("volume", models.IntegerField()),
                ("period", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="DayPrice",
        ),
        migrations.DeleteModel(
            name="NightPrice",
        ),
    ]
