# Generated by Django 5.0.6 on 2024-05-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_pricedata_delete_dayprice_delete_nightprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settlement",
            name="date",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
