# Generated by Django 5.0.6 on 2024-05-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_order_date_remove_order_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deal_price",
            field=models.FloatField(),
        ),
    ]
