# Generated by Django 5.0.6 on 2024-07-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_diff_price_revenue_gain_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtest",
            name="fr_trading_signal",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="backtest",
            name="tw_trading_signal",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="signal",
            name="fr_trading_signal",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="signal",
            name="tw_trading_signal",
            field=models.IntegerField(default=0),
        ),
    ]
