# Generated by Django 5.0.6 on 2024-05-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_settlement_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backtest",
            name="option_data",
        ),
        migrations.RemoveField(
            model_name="backtest",
            name="signal_data",
        ),
        migrations.RemoveField(
            model_name="order",
            name="signal_data",
        ),
        migrations.RemoveField(
            model_name="revenue",
            name="order_data",
        ),
        migrations.RemoveField(
            model_name="revenue",
            name="signal_data",
        ),
        migrations.RemoveField(
            model_name="signal",
            name="option_data",
        ),
    ]
