# Generated by Django 5.2.4 on 2025-08-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_traders_tradingparameters"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Traders",
        ),
        migrations.DeleteModel(
            name="TradingParameters",
        ),
    ]
