# Generated by Django 5.2.4 on 2025-08-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_delete_traders_delete_tradingparameters"),
    ]

    operations = [
        migrations.CreateModel(
            name="Traders",
            fields=[
                ("trader_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("personal_id", models.CharField(max_length=20)),
                (
                    "product",
                    models.CharField(
                        choices=[("TX", "TXF"), ("MTX", "MXF")], max_length=64
                    ),
                ),
                ("product_count", models.IntegerField(default=0)),
                ("shioaji_api_key", models.CharField(max_length=256)),
                ("shioaji_secret_key", models.CharField(max_length=256)),
                ("shioaji_ca_path", models.CharField(max_length=256)),
                ("line_token", models.CharField(max_length=256)),
                ("line_user_id", models.CharField(max_length=256)),
                ("line_notify", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TradingParameters",
            fields=[
                ("parameters_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Mon", "Mon"),
                            ("Tue", "Tue"),
                            ("Wed", "Wed"),
                            ("Thu", "Thu"),
                            ("Fri", "Fri"),
                        ],
                        max_length=10,
                    ),
                ),
                ("threshold", models.IntegerField(default=0)),
                ("count", models.IntegerField(default=0)),
                ("reverse", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
