# Generated by Django 5.2.4 on 2025-08-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_traders_tradingparameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingparameters",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
